server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  # - url: http://192.168.57.2:3100/loki/api/v1/push
  - url: ${LOKI_URL}
    # - url: http://mario:test123@192.168.57.2/loki
    basic_auth:
      username: ${LOKI_BASIC_AUTH_USER}
      password: ${LOKI_BASIC_AUTH_PW}

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: server_logs
          __path__: /var/log/*log
      - targets:
          - localhost
        labels:
          job: test_logs
          __path__: /var/log/test/*log

  # - job_name: containers
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: remote_logs
  #         instance: "$LOKI_IP"
  #         __path__: /var/lib/
