version: "3"

networks:
  loki_nw:

services:
  loki:
    image: grafana/loki:2.9.0
    # ports:
    #   - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki_nw

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    # ports:
    #   - "3000:3000"
    networks:
      - loki_nw

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./loki.htpasswd:/etc/nginx/loki.htpasswd
      # - ./loki.conf:/etc/nginx/conf.d/loki.conf
      # - ./simple.conf:/etc/nginx/conf.d/loki.conf
      - ./simple.conf:/etc/nginx/nginx.conf

    depends_on:
      - loki
    networks:
      - loki_nw
    restart: always
  # nginx:
  #   image: laurentbel/nginx-basic-auth
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - loki
  #   environment:
  #     - FORWARD_HOST=loki
  #     - FORWARD_PORT=3100
  #     - BASIC_USERNAME=$BASIC_USERNAME
  #     - BASIC_PASSWORD=$BASIC_PASSWORD
  #   networks:
  #     - loki
